In [2]:
import numpy as np

In [2]:
my_arr = np.array([[13,32,12]], np.int8)

In [3]:
my_arr

array([[13, 32, 12]], dtype=int8)

In [4]:
my_arr[0,2]

np.int8(12)

In [5]:
my_arr[0,2] = 45

# Array Creation: Convenrsion from other Python Structers.


In [6]:
list_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
list_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list_arr.dtype

dtype('int64')

In [9]:
list_arr.shape

(3, 3)

In [10]:
list_arr.size

9

In [11]:
np.array({1,2,4})

array({1, 2, 4}, dtype=object)

In [12]:
zeros = np.zeros((2,4)) # it generally creates array of zeros of dimension 2*5.

In [13]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
rng = np.arange(45,50) # privide a numpy array from 45 to 49


In [4]:
rng

array([45, 46, 47, 48, 49])

In [16]:
rng1 = np.arange(15) # or np.range(0,15) bot are same

In [17]:
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
lspace = np.linspace(1,12,6) # this will provide me 6 equally spaced array b\w 1 to 12 including 1 and 12.

In [7]:
lspace

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [8]:
emp = np.empty((4,6)) # this will provide me array of dimension 4*6 filled with the random elements.

In [10]:
print(emp)
emp.shape

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.11260755e-306
  1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 1.37962320e-306 1.29060871e-306
  2.22518251e-306 1.33511969e-306]
 [1.78022342e-306 1.05700345e-307 3.11525958e-307 1.69118108e-306
  8.06632139e-308 1.20160711e-306]
 [1.69119330e-306 1.29062229e-306 1.24610383e-306 1.69118108e-306
  7.56599128e-307 1.42410974e-306]]


(4, 6)

In [22]:
emp_like = np.empty_like(lspace) # this will make a copy of "lspace". we use "empty_like" for the efficiency, for making a another array as same lengh as old one.

In [23]:
emp_like

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [24]:
ide = np.identity(12) # this will provide me a identity matrix of dimension 12*12.

In [25]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Reshape
while reshaping a array you reshaped value should be equal to the number of element in the reshaped array.

Example:
    If your array having 6-elements, then you can only reshape it as (1,6), (2,3), (3,2) and (6,1)
    here (1,6) means your reshaped array will have 1 row and 6 element in it.
    Similiary (3,2) means you reshaped array while have 3 rows and 2 coloumn.

In [26]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)

print(f'the shape of var array is: {var.shape}')
print(f'the dimension of this array is: {var.ndim}')

[[1 2 3 4]
 [1 2 3 4]]
the shape of var array is: (2, 4)
the dimension of this array is: 2


In [27]:
var1 = np.array([1,2,3,4,5,6])

#if you want to reshape your arrang like (2*3) of (3*2)
x = var1.reshape(2,3)
y = var1.reshape(3,2)
print(x)
print(x.shape)
print(f' dimension of this array is: {x.ndim}')
print()
print(y)
print(y.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
 dimension of this array is: 2

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [28]:
# Creating a # dimensional array
var2 = np.arange(1,13)
print(var2)

z = var2.reshape(2,3,2) # we has reshaped a array into a 3 dimensional array.
print(f'this is a 3 dimensional array:\n{z}')

print(f'Reshaping a 3 dimensional array into 1 dimensional array: \n{z.reshape(-1)}')

[ 1  2  3  4  5  6  7  8  9 10 11 12]
this is a 3 dimensional array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Reshaping a 3 dimensional array into 1 dimensional array: 
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Numpy Axis

1D = [1,2,3,4,5] --> 1 [Axis0]
2D = [[1,2,3],[3,4,2]] --> 2 [Axis0, Axis1]
.
.
.
nD = [[1,2,3,5,32,....].......,[4,5,2,1,....]] --> n [Axis0, Axis1,....., Axisn]

In [29]:
x = [[1,2,3],[4,7,6],[7,8,0]]
arr = np.array(x)

In [30]:
arr

array([[1, 2, 3],
       [4, 7, 6],
       [7, 8, 0]])

In [31]:
arr.sum(axis=0)

array([12, 17,  9])

In [32]:
arr.sum(axis=1)

array([ 6, 17, 15])

In [33]:
arr.T # this will transpose my arr

array([[1, 4, 7],
       [2, 7, 8],
       [3, 6, 0]])

In [34]:
arr.ndim # this tell us the dimension of the array. 

2

In [35]:
arr.size# return number of elements of array.

9

In [36]:
one = np.array([1,3,45,23,5,67])



In [37]:
one.argmax() # this returns the index number of max value element.

np.int64(5)

In [38]:
one.argmin() # returns the index of the minimum array.

np.int64(0)

In [39]:
one.argsort() # this return the array of indexes in the sorted form i.e in accending order.

array([0, 1, 4, 3, 2, 5])

lets see what will happen when we use thse "function" over 2D array.

In [40]:
arr

array([[1, 2, 3],
       [4, 7, 6],
       [7, 8, 0]])

In [41]:
arr.argmin() 

np.int64(8)

In [42]:
arr.argmax()

np.int64(7)

In [43]:
arr.argmax(axis = 0) # this wil returns the indexes of largest element from each of the axis=0.

array([2, 2, 1])

In [44]:
arr.argmin(axis = 1)

array([0, 0, 2])

In [45]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 2, 1],
       [2, 0, 1]])

In [46]:
arr.argsort(axis = 0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]])